# This config file is meant for settings that affect your whole blog, values which you are expected to set up once and rarely need to edit after that.
# If you find yourself editing this file very often, consider using Jekyll's # data files feature for the data you need to update frequently.
# For technical reasons, this file is *NOT* reloaded automatically when you use 'jekyll serve'. If you change this file, please restart the server process.

### Site settings ###
# These are used to personalize your new site. If you look in the HTML files, you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible in the templates via {{ site.myvariable }}.

title: Portfolio
# email: not sure if I should attach this
description: Portfolio
# Natalie is ______
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "https://nat-JT.github.io" # the base hostname & protocol for your site
##url: http://127.0.0.1:4000
repository: "Nat-JT/nat-jt.github.io"

### Logo settings ###
# logo-image-url: 
# font-awesome-icon-logo:

### Social settings ###
#linkedin_username: nterenzi
#linkedin_path: https://www.linkedin.com/naterenzi
#github_username: 
#phone: 555-5555

path-to-CS-images: /assets/images/case-studies/

### Build settings ###
permalink: pretty
markdown: kramdown
#theme: 
plugins:
  - jekyll-feed

# Exclude from processing. 
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to the internal "default list".
# Excluded items can be processed by explicitly listing the directories or their entries' file path in the `include:` list.

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
  style: compressed

# Whenever it compiles sass into CSS it will compress CSS so it's minimized

collections:
  case-studies:
    output: true
    permalink: /case-studies/:path/
